name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute commands on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: www
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/www/finman/finman_api
          git pull origin main
          docker compose down
          docker compose up -d --build