name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: www
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*"
        target: "/home/www/finman/finman_api"
        strip_components: 0

    - name: Execute commands on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: www
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/www/finman/finman_api
          docker compose down
          docker compose up -d --build